### PR TITLE
5213: fix load for search select field and disabled options

### PR DESCRIPTION
**Pull request by transitorytammy**

### CODE REVIEW

**Comment by amacdougall** [comment]
`autocomplete=nope`?

**Comment by transitorytammy** [comment]
yeah...seems more stable than `off`.

https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion

**Comment by amacdougall** [comment]
Whoa, you learn something new every day.

**Comment by transitorytammy** [comment]
.25 days in January

**Pull request merged**
